import type { Language } from './types';

export const LANGUAGES: Language[] = [
    { code: 'pt-PT', name: 'Português (PT)', flag: '🇵🇹' },
    { code: 'pt-BR', name: 'Português (BR)', flag: '🇧🇷' },
    { code: 'en-US', name: 'English', flag: '🇬🇧' },
    { code: 'es-ES', name: 'Español', flag: '🇪🇸' },
    { code: 'fr-FR', name: 'Français', flag: '🇫🇷' },
    { code: 'de-DE', name: 'Deutsch', flag: '🇩🇪' },
    { code: 'it-IT', name: 'Italiano', flag: '🇮🇹' },
    { code: 'nl-NL', name: 'Nederlands', flag: '🇳🇱' },
    { code: 'pl-PL', name: 'Polski', flag: '🇵🇱' },
    { code: 'sv-SE', name: 'Svenska', flag: '🇸🇪' },
    { code: 'da-DK', name: 'Dansk', flag: '🇩🇰' },
    { code: 'fi-FI', name: 'Suomi', flag: '🇫🇮' },
    { code: 'cs-CZ', name: 'Čeština', flag: '🇨🇿' },
    { code: 'el-GR', name: 'Ελληνικά', flag: '🇬🇷' },
    { code: 'hu-HU', name: 'Magyar', flag: '🇭🇺' },
    { code: 'ro-RO', name: 'Română', flag: '🇷🇴' },
    { code: 'sk-SK', name: 'Slovenčina', flag: '🇸🇰' },
    { code: 'bg-BG', name: 'Български', flag: '🇧🇬' },
    { code: 'hr-HR', name: 'Hrvatski', flag: '🇭🇷' },
    { code: 'et-EE', name: 'Eesti', flag: '🇪🇪' },
    { code: 'ga-IE', name: 'Gaeilge', flag: '🇮🇪' },
    { code: 'lt-LT', name: 'Lietuvių', flag: '🇱🇹' },
    { code: 'lv-LV', name: 'Latviešu', flag: '🇱🇻' },
    { code: 'mt-MT', name: 'Malti', flag: '🇲🇹' },
    { code: 'sl-SI', name: 'Slovenščina', flag: '🇸🇮' },
];
